sudo: required
dist: trusty
language: java
node_js:
  - "7"
jdk:
  - oraclejdk8
env:
  - CXX=g++-4.8
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - export CHROME_BIN=chromium-browser
 - echo "--no-sandbox" > ~/.config/chromium-flags.conf
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  apt: true
  yarn: true
  directories:
  - build/nodejs
  - build/npm
  - build/yarn
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
after_success:
  - bash <(curl -s https://codecov.io/bash)
