sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
env:
  - CXX=g++-4.8
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - export CHROME_BIN=google-chrome
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  apt: true
  yarn: true
  directories:
  - build/nodejs
  - build/npm
  - build/yarn
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - g++-4.8
    - google-chrome-stable
after_success:
  - bash <(curl -s https://codecov.io/bash)
